// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxDIqUdbvrh_7X4xgESUI7zM7rkH2kW0',
    appId: '1:295551301891:web:ebe6b80463bf8945609136',
    messagingSenderId: '295551301891',
    projectId: 'modul3-7d03f',
    authDomain: 'modul3-7d03f.firebaseapp.com',
    storageBucket: 'modul3-7d03f.appspot.com',
    measurementId: 'G-6VKKE5C79J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDff4YBnKJzDyh2TLnmEVM978Z4I_64t2s',
    appId: '1:295551301891:android:ca1c01296c6e82ef609136',
    messagingSenderId: '295551301891',
    projectId: 'modul3-7d03f',
    storageBucket: 'modul3-7d03f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOfK9IeBhllt3sAvCjUAOYgpH-xhcbK-E',
    appId: '1:295551301891:ios:ff3799ba0d2dba3d609136',
    messagingSenderId: '295551301891',
    projectId: 'modul3-7d03f',
    storageBucket: 'modul3-7d03f.appspot.com',
    iosBundleId: 'com.yusril.codelab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOfK9IeBhllt3sAvCjUAOYgpH-xhcbK-E',
    appId: '1:295551301891:ios:ff3799ba0d2dba3d609136',
    messagingSenderId: '295551301891',
    projectId: 'modul3-7d03f',
    storageBucket: 'modul3-7d03f.appspot.com',
    iosBundleId: 'com.yusril.codelab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhxDIqUdbvrh_7X4xgESUI7zM7rkH2kW0',
    appId: '1:295551301891:web:2e2c082b8453f804609136',
    messagingSenderId: '295551301891',
    projectId: 'modul3-7d03f',
    authDomain: 'modul3-7d03f.firebaseapp.com',
    storageBucket: 'modul3-7d03f.appspot.com',
    measurementId: 'G-7EJELWE5SF',
  );
}
